databaseChangeLog = {

  changeSet(author: "Diogo Cabral de Almeida", id: "281020161415") {

    addForeignKeyConstraint(constraintName: "profile_institution_id_fkey", baseColumnNames: "institution_id", baseTableName: "profile", referencedColumnNames: "id", referencedTableName: "institution")
    addForeignKeyConstraint(constraintName: "license_pack_institution_id_fkey", baseColumnNames: "institution_id", baseTableName: "license_pack", referencedColumnNames: "id", referencedTableName: "institution")
    addForeignKeyConstraint(constraintName: "pendency_institution_id_fkey", baseColumnNames: "institution_id", baseTableName: "pendency", referencedColumnNames: "id", referencedTableName: "institution")
    addForeignKeyConstraint(constraintName: "user_institution_institution_id_fkey", baseColumnNames: "institution_id", baseTableName: "user_institution", referencedColumnNames: "id", referencedTableName: "institution")
    addForeignKeyConstraint(constraintName: "user_institution_id_fkey", baseColumnNames: "institution_id", baseTableName: "user", referencedColumnNames: "id", referencedTableName: "institution")
    addForeignKeyConstraint(constraintName: "cluster_institution_id_fkey", baseColumnNames: "institution_id", baseTableName: "cluster", referencedColumnNames: "id", referencedTableName: "institution")
    addForeignKeyConstraint(constraintName: "license_institution_id_fkey", baseColumnNames: "institution_id", baseTableName: "license", referencedColumnNames: "id", referencedTableName: "institution")
    addForeignKeyConstraint(constraintName: "license_type_id_fkey", baseColumnNames: "type_id", baseTableName: "license", referencedColumnNames: "id", referencedTableName: "license_type")
    addForeignKeyConstraint(constraintName: "submission_language_id_fkey", baseColumnNames: "language_id", baseTableName: "submission", referencedColumnNames: "id", referencedTableName: "language")
    addForeignKeyConstraint(constraintName: "problem_fastest_submission_id_fkey", baseColumnNames: "fastest_submission_id", baseTableName: "problem", referencedColumnNames: "id", referencedTableName: "submission")
    addForeignKeyConstraint(constraintName: "plagiarism_submission1_id_fkey", baseColumnNames: "submission1_id", baseTableName: "plagiarism", referencedColumnNames: "id", referencedTableName: "submission")
    addForeignKeyConstraint(constraintName: "plagiarism_submission2_id_fkey", baseColumnNames: "submission2_id", baseTableName: "plagiarism", referencedColumnNames: "id", referencedTableName: "submission")
    addForeignKeyConstraint(constraintName: "user_role_role_id_fkey", baseColumnNames: "role_id", baseTableName: "user_role", referencedColumnNames: "id", referencedTableName: "role")
    addForeignKeyConstraint(constraintName: "topic_problems_topic_id_fkey", baseColumnNames: "topic_id", baseTableName: "topic_problems", referencedColumnNames: "id", referencedTableName: "topic")
    addForeignKeyConstraint(constraintName: "message_group_id_fkey", baseColumnNames: "group_id", baseTableName: "message", referencedColumnNames: "id", referencedTableName: "cluster")
    addForeignKeyConstraint(constraintName: "questionnaire_group_id_fkey", baseColumnNames: "group_id", baseTableName: "questionnaire", referencedColumnNames: "id", referencedTableName: "cluster")
    addForeignKeyConstraint(constraintName: "user_cluster_cluster_id_fkey", baseColumnNames: "cluster_id", baseTableName: "user_cluster", referencedColumnNames: "id", referencedTableName: "cluster")
    addForeignKeyConstraint(constraintName: "pendency_group_id_fkey", baseColumnNames: "group_id", baseTableName: "pendency", referencedColumnNames: "id", referencedTableName: "cluster")
    addForeignKeyConstraint(constraintName: "questionnaire_user_penalty_questionnaire_user_id_fkey", baseColumnNames: "questionnaire_user_id", baseTableName: "questionnaire_user_penalty", referencedColumnNames: "id", referencedTableName: "questionnaire_user")
    addForeignKeyConstraint(constraintName: "message_message_message_id_fkey", baseColumnNames: "message_id", baseTableName: "message_message", referencedColumnNames: "id", referencedTableName: "message")
    addForeignKeyConstraint(constraintName: "message_message_message_responses_id_fkey", baseColumnNames: "message_responses_id", baseTableName: "message_message", referencedColumnNames: "id", referencedTableName: "message")
    addForeignKeyConstraint(constraintName: "topic_problems_problem_id_fkey", baseColumnNames: "problem_id", baseTableName: "topic_problems", referencedColumnNames: "id", referencedTableName: "problem")
    addForeignKeyConstraint(constraintName: "user_problem_problem_id_fkey", baseColumnNames: "problem_id", baseTableName: "user_problem", referencedColumnNames: "id", referencedTableName: "problem")
    addForeignKeyConstraint(constraintName: "test_case_problem_id_fkey", baseColumnNames: "problem_id", baseTableName: "test_case", referencedColumnNames: "id", referencedTableName: "problem")
    addForeignKeyConstraint(constraintName: "questionnaire_problem_problem_id_fkey", baseColumnNames: "problem_id", baseTableName: "questionnaire_problem", referencedColumnNames: "id", referencedTableName: "problem")
    addForeignKeyConstraint(constraintName: "submission_problem_id_fkey", baseColumnNames: "problem_id", baseTableName: "submission", referencedColumnNames: "id", referencedTableName: "problem")
    addForeignKeyConstraint(constraintName: "submission_plagiarism_status_id_fkey", baseColumnNames: "plagiarism_status_id", baseTableName: "submission", referencedColumnNames: "id", referencedTableName: "plagiarism_status")
    addForeignKeyConstraint(constraintName: "questionnaire_user_questionnaire_id_fkey", baseColumnNames: "questionnaire_id", baseTableName: "questionnaire_user", referencedColumnNames: "id", referencedTableName: "questionnaire")
    addForeignKeyConstraint(constraintName: "questionnaire_problem_questionnaire_id_fkey", baseColumnNames: "questionnaire_id", baseTableName: "questionnaire_problem", referencedColumnNames: "id", referencedTableName: "questionnaire")
    addForeignKeyConstraint(constraintName: "questionnaire_user_penalty_questionnaire_problem_id_fkey", baseColumnNames: "questionnaire_problem_id", baseTableName: "questionnaire_user_penalty", referencedColumnNames: "id", referencedTableName: "questionnaire_problem")
    addForeignKeyConstraint(constraintName: "pendency_user_id_fkey", baseColumnNames: "user_id", baseTableName: "pendency", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "questionnaire_user_user_id_fkey", baseColumnNames: "user_id", baseTableName: "questionnaire_user", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "submission_user_id_fkey", baseColumnNames: "user_id", baseTableName: "submission", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "problem_user_suggest_id_fkey", baseColumnNames: "user_suggest_id", baseTableName: "problem", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "profile_user_id_fkey", baseColumnNames: "user_id", baseTableName: "profile", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "top_coder_user_id_fkey", baseColumnNames: "user_id", baseTableName: "top_coder", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "problem_user_approved_id_fkey", baseColumnNames: "user_approved_id", baseTableName: "problem", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "user_problem_user_id_fkey", baseColumnNames: "user_id", baseTableName: "user_problem", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "feed_recipient_id_fkey", baseColumnNames: "recipient_id", baseTableName: "feed", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "user_cluster_user_id_fkey", baseColumnNames: "user_id", baseTableName: "user_cluster", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "user_institution_user_id_fkey", baseColumnNames: "user_id", baseTableName: "user_institution", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "message_sender_id_fkey", baseColumnNames: "sender_id", baseTableName: "message", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "user_role_user_id_fkey", baseColumnNames: "user_id", baseTableName: "user_role", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "message_recipient_id_fkey", baseColumnNames: "recipient_id", baseTableName: "message", referencedColumnNames: "id", referencedTableName: "user")
    addForeignKeyConstraint(constraintName: "license_user_id_fkey", baseColumnNames: "user_id", baseTableName: "license", referencedColumnNames: "id", referencedTableName: "user")

  }

}